server:
  port: 8081
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_app
    username: postgres
    password: postgres
    
  jpa:
    generate-ddl: true
    show-sql: true